foodtruckhub/urls.py
from django.contrib import admin
from django.urls import path, include
from hubapp import views as core_views
from django.contrib.auth import views as auth_views
from hubapp.views import Home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_app.urls')),
    path('', include('hubapp.urls')),
    path("accounts/", include("allauth.urls")),
    path('Home', Home.as_view(), name="home"),
]

hubapp/urls.py
from django.urls import path, include
from hubapp import views



app_name = 'hubapp'

urlpatterns = [
    path('display/', views.display, name='display'),
    path('controller/', views.controller, name='controller'),
    path('whereami/', views.whereami, name='whereami'),
    path('test/', views.test, name='test'),

    
] 

user_app/urls.py
from django.urls import path
from . import views


app_name = 'user_app'

urlpatterns = [

    path('login', views.ulogin, name='ulogin'),
    path('', views.base, name='base'),
    path('dashboard/<str:username>', views.profile, name = 'profile'),
    path('register/', views.register, name = 'register'),
    path('logout/', views.logout, name = 'logout'),
    path('accounts/dashboard/', views.profile, name = 'profile'),
    path('delete', views.delete, name = 'delete'),
    path('privacy', views.privacy, name = 'privacy'),

    # path('accounts/login/', views.login, name='login'),


] 

user_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.



class User(AbstractUser):
    
    username = models.CharField(max_length=23, unique = True)

    is_a_superuser = models.BooleanField(default=False, verbose_name='Admin Dashboard Access')

    def __str__(self):
    
        return self.username

user_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import (
    login as django_login,
    logout as django_logout,
    authenticate,
    get_user_model 
)

from .models import User

# Create your views here.
def base(request):

    return render(request, 'base.html')


def register(request):

    if request.method == 'GET':
    
        return render(request, 'user_app/register.html')
    
    elif request.method == 'POST':

        form = request.POST

        username = form.get('username')

        password = form.get('password')

        first_name = form.get('first-name')

        last_name = form.get('last-name')

        email = form.get('email')

        user = User.objects.create_user(

            first_name=first_name,
            last_name=last_name,
            email=email,
            username=username,
            password=password,
            
        )

        django_login(request, user)

        return redirect(reverse('user_app:profile', kwargs={ 'username': user.username}))    

# --------------------------------------------------------
def delete(request):

    del request.user

    return render(request, 'base.html')

def privacy(request):

    return render(request, 'privacy.html')

def ulogin(request):

    if request.method == 'GET':

        return render(request, 'registration/login.html')

    elif request.method == 'POST':

        form = request.POST

        username = form.get('username')

        password = form.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:

            django_login(request, user) 

        return redirect(reverse('user_app:profile', kwargs={ 'username': username}))




# --------------------------------------------------------
@login_required
def profile(request, username):

    if request.method == 'GET':

        user = get_object_or_404(get_user_model(), username=username)

        context = {

            'username': request.user,
            
        }

        return render(request, 'user_app/mem-dashboard.html', context)



# --------------------------------------------------------

def logout(request):

    django_logout(request)

    return redirect('user_app:base')

templates/user_app/register.html
{% load static %}

<!DOCTYPE html>

<html lang="en"><head>
    <meta charset="utf-8">
    <title>witness</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
  
    
    
</head>

<body>
    {% include 'navbar.html' %}
    <div class="card" id="tester">
        test
    </div>
    <section class="container-fluid " >
        <div>
            <form action="{% url 'user_app:register' %}" method="POST">
                <div class="row">
                    <div class=" col-12 d-flex justify-content-center align-items-center">
                        <div class="card mx-2 mt-3 mb-3 col-6" style="border: 2px solid black">
                            <div class="mb-1 p-2 col-12">
                                <label for="username" class="form-label"></label>
                                <input type="text" class="form-control" id="username" name="username"
                                    placeholder="Username">
                            </div>
                            <div class="mb-1 p-2 col-12">
                                <label for="email" class="form-label"></label>
                                <input type="text/email" class="form-control" id="email" name="email" placeholder="Email">
                            </div>
                            <div class="mb-1 p-2 col-12" id ='complexity'>
                                <label for="password" class="form-label"></label>
                                <input type="password" class="form-control" id="password" name="password"
                                    placeholder="password">
                                    <span id="first_estimate">a</span>
                                    <span id='complexity-span'>b</span>
                                    <span id='character_count'>c</span>

                            </div>
                            <div class="mb-1 p-2 col-12">
                                <label for="first-name" class="form-label"></label>
                                <input type="text" class="form-control" id="first-name" name="first-name"
                                    placeholder="First Name">
                            </div>
                            <div class="mb-1 p-2 col-12">
                                <label for="last-name" class="form-label"></label>
                                <input type="text" class="form-control" id="last-name" name="last-name"
                                    placeholder="Last Name">
                            </div>
                            <button type="submit" class="btn btn-dark mt-3 mx-5">Sign Up</button>
                            <p class="d-flex justify-content-center align-items-center">Already have an account? <a
                                    href="{% url 'user_app:ulogin' %}" class="link-primary text-decoration-none">Log In</a>
                            </p>
                            {% csrf_token %}
                        </div>
                    </div>
                </div>
            </form>
        <div>
    </section>
    <script src="{% static 'js/test.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</body>