foodtruckhub/urls.py
from django.contrib import admin
from django.urls import path, include
from hubapp import views as core_views
from django.contrib.auth import views as auth_views
from hubapp.views import Home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_app.urls')),
    path('', include('hubapp.urls')),
    path("accounts/", include("allauth.urls")),
    path('Home', Home.as_view(), name="home"),
]

hubapp/urls.py
from django.urls import path, include
from hubapp import views



app_name = 'hubapp'

urlpatterns = [
    path('display/', views.display, name='display'),
    path('controller/', views.controller, name='controller'),
    path('whereami/', views.whereami, name='whereami'),
    path('test/', views.test, name='test'),

    
] 

user_app/urls.py
from django.urls import path
from . import views


app_name = 'user_app'

urlpatterns = [

    path('login', views.ulogin, name='ulogin'),
    path('', views.base, name='base'),
    path('dashboard/<str:username>', views.profile, name = 'profile'),
    path('register/', views.register, name = 'register'),
    path('logout/', views.logout, name = 'logout'),
    path('accounts/dashboard/', views.profile, name = 'profile'),
    path('delete', views.delete, name = 'delete'),
    path('privacy', views.privacy, name = 'privacy'),

    # path('accounts/login/', views.login, name='login'),


] 

templates/base.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>

<html lang="en">
  <head>
  <meta charset="utf-8">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/pig_logo-final.png' %}"/>
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

  
  
  </head>

  <body id="main-page">
    <section id="hero" class="  container-fluid">
      
      <a href="" style="text-decoration:none">
        <h1 class=" d-flex justify-content-center align-items-center pt-5 text-light">
          FOODTRUCK 
            <span class="neonText">
              .HELP
  
            </span>

          </h1>
        </a>
        <p class='d-flex justify-content-center align-items-center text-light'>Your favourite trucks all in one place</p>
  
        
        
    </section>
    <img id="main-image" src="/static/images/landing-page-bg.jpg" alt="" srcset="">
    <a href="{% url 'user_app:register' %}" class="" style="text-decoration:none">
      <div id="get-started" class="button1 shadow-lg">Get Started</div>
    </a>
    <span id="signin1" class="text-light">Sign in with</span>
    <!-- <a id="icons" href="https://www.flaticon.com/free-icons/facebook" title="facebook icons"></a> -->
    
      <a href="{% provider_login_url 'facebook' %}">
        <img class="" id="icons" src="/static/images/facebook.png" alt="Facebook icons created by Ruslan Babkin - Flaticon" srcset="">
      </a>
      <a href="#">
        <img id="icons" src="/static/images/google.png" alt="Google icons created by Ruslan Babkin - Flaticon" srcset="">
      </a>
      <a href="{% provider_login_url 'twitter' %}">
        <img id="icons" src="/static/images/twitter.png" alt="Facebook icons created by Ruslan Babkin - Flaticon" srcset="">
      </a>

      <span class="text-muted" id="signup">Don't have an account? <a href="{% url 'user_app:register' %}"style="text-decoration:none">Sign Up</a></span>

    
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/ScrollTrigger.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/Draggable.min.js"></script>
    <script type="text/javascript" src="{% static '\js\animate.js' %}"></script>

  </body>

</html>

templates/footer.html
<footer class="container-fluid " id="foot">
    <div class="row">
        <div class="col-12 mt-4 pt-0 d-flex justify-content-center align-items-center" order: 1>

        </div>
        <div class="col-12 gap-5 pb-3 d-flex justify-content-around align-items-center" order: 2>
            {% if request.user.is_authenticated %}
            <a href="{% url 'user_app:logout' %}" class="link-light text-decoration-none" id="link">Logout</a>{% endif %}
            <a href="#" class="link-dark text-decoration-none" id="link">Menu</a>
            <a href="#" class="link-dark text-decoration-none" id="link">Contact</a>
            <a href="#" class="link-dark text-decoration-none" id="link">About Us</a>
            <a href="{% url 'hubapp:whereami' %}" class="link-dark text-decoration-none" id="link">Where Am I?</a>

        </div>
    </div>
</footer>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TRUCKS</title>
</head>
<body>
    <h1>HOME</h1>
    <h2>welcome {{user.username}}</h2>

    <!-- <h2>First Name: {{user.first_name}}</h2>
    <h2>Last Name: {{user.last_name}}</h2>
    <h2>Date joined: {{user.date_joined}}</h2>
    <h2>id: {{user.id}}</h2>
    <h2>{{user}}</h2> -->
    <a href="{% url 'account_logout' %}" class="btn btn-danger">Logout</a>

    {% for a in all_fields %}
    <h1>{{a}}</h1>{% endfor %}

</body>
</html>

templates/privacy.html
privacy policy